package me.shadow.cobalt.core.model

/**
 * Machine-readable failure codes for session errors.
 */
enum class FailureCode {
    VERSION_UNRESOLVED,
    VERSION_AMBIGUOUS,
    UNSUPPORTED_ABI,
    EGL_CONTEXT_UNAVAILABLE,
    GLES_TOO_LOW,
    LIBRARY_MISSING,
    SYMBOL_MISSING,
    CONTEXT_CREATION_FAILED,
    MINIMAL_DRAW_FAILED,
    PRESENT_FAILED,
    SURFACE_RECONFIGURE_FAILED,
    CONTEXT_LOST,
    SHADER_COMPILE_FAILED,
    SHADER_TRANSLATION_FAILED,
    CACHE_CORRUPTED,
    CACHE_WRITE_FAILED,
    CACHE_UNAVAILABLE,
    MEMORY_PRESSURE,
    NATIVE_CRASH,
    RETRY_BUDGET_EXHAUSTED,
    PROVIDER_INIT_FAILED,
    PROVIDER_REJECTED,
    INTERNAL_ERROR
}
